# Weather Sensors MQTT Stack for Portainer
# Copy this entire file content into Portainer > Stacks > Add Stack > Web Editor

# =============================================================================
# PUB_SOURCE is a tag or identifier for the host on which the service is running
# it can be the hostname or a friendly name for the host, and is used to identify 
# the "location" part of the topic string when using an ISA95 like hierarchy for 
# the topic string (eg: enterprise/site/area/line/cell...).  In this case, the
# 'site' is the host which is publishing the information.
#   - Mu is the default, and will identify that the PUB_SOURCE variable is not
# properly set.
#
# NOTE: You must update PUB_SOURCE in BOTH service environment sections below
# (lines ~54 and ~108) when deploying to different hosts.
# =============================================================================

###############################################################################
# NETWORK CONFIGURATION
###############################################################################

networks:
  weather-sensors:
    driver: bridge
    name: weather-sensors-network

volumes:
  sensor-data:
    name: weather-sensors-data
    driver: local
  sensor-logs:
    name: weather-sensors-logs
    driver: local
  sensor-config:
    name: weather-sensors-config
    driver: local

###############################################################################
# SENSOR REPUBLISHER SERVICE
# Services section for the weather sensors republishing service
###############################################################################

services:
  # RTL-433 Sensor Data Republisher Service
  sensor-republisher:
    image: karltbraun/weather-sensors:latest
    pull_policy: always
    container_name: weather-sensors-republisher
    restart: on-failure:3
    ###############################################################################
    # NETWORK CONFIGURATION (Choose ONE per deployment scenario)
    # HOME LAB: Use bridge networking (default)
    #   - Leave 'networks:' assignment below uncommented
    #   - Keep 'network_mode: host' commented out
    # VM/Host: Use host networking
    #   - Uncomment 'network_mode: host' below
    #   - Comment/remove 'networks:' assignment below
    # Example:
    #   network_mode: host
    #   # networks:
    #   #   - weather-sensors
    ###############################################################################
    # network_mode: host
    networks:
      - weather-sensors
    volumes:
      - sensor-data:/app/data
      - sensor-logs:/app/logs
      - sensor-config:/app/config
    ###############################################################################
    # ENVIRONMENT VARIABLES
    # Set broker_name and PUB_SOURCE as needed for your deployment
    #  BROKER_NAME should reference an entry in broker_config.py
    #  PUB_SOURCE should be a unique identifier for the host publishing the data
    #  PUB_TOPIC_ROOT would be the first level in the topic string
    #  SUB_TOPICS_REPUBLISH should match the topics published by your raw sensors
    #      This is the topic expresion to which the RTL_433 program(s) are publishing 
    #      raw data.
    #  SUB_TOPIC_CONFIG_UPDATE is the topic on which configuration updates are made
    #      as of 2025-11-20, this is mainly for future enhancements
    ###############################################################################
    environment:
      - DEPLOYMENT_SCENARIO=home-lab
      - PUB_SOURCE=Mu
      - BROKER_NAME=n-vultr2
      - TZ=America/Los_Angeles
      - PUBLISH_INTERVAL_MAX=60
      - SERVICE=republish
      - CONSOLE_LOG_LEVEL=INFO
      - FILE_LOG_LEVEL=DEBUG
      - CLEAR_LOG_FILE=true
      - MQTT_CONFIG_INFO={}
      - PUB_TOPIC_ROOT=KTBMES
      - SUB_TOPICS_REPUBLISH=+/sensors/raw/#
      - MQTT_TOPIC_LOCAL_SENSORS_UPDATES=KTBMES/ROSA/sensors/config/local_sensors/update
      - MQTT_TOPIC_LOCAL_SENSORS_CURRENT=KTBMES/VULTR/sensors/config/local_sensors/current
      - SUB_TOPICS_REPUBLISH=+/sensors/raw/#,KTBMES/ROSA/sensors/config/local_sensors/update
      - MAX_BACKUPS=10
      - BACKUP_RETENTION_DAYS=30
    labels:
      - "portainer.group=weather-sensors"
      - "portainer.service=republisher"
      - "description=RTL-433 sensor data republisher service"
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/logs/republish_processed_sensors.log') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'


###############################################################################
# SHELLY ENERGY MONITOR PROCESSOR SERVICE
# Services section for the shelly-processor servce
###############################################################################

  # Shelly Smart Device Processor Service
  shelly-processor:
    image: karltbraun/weather-sensors:latest
    pull_policy: always
    container_name: shelly-processor
    restart: on-failure:3
    ###############################################################################
    # NETWORK CONFIGURATION (Choose ONE per deployment scenario)
    # HOME LAB: Use bridge networking (default)
    #   - Leave 'networks:' assignment below uncommented
    #   - Keep 'network_mode: host' commented out
    # VM/Host: Use host networking
    #   - Uncomment 'network_mode: host' below
    #   - Comment/remove 'networks:' assignment below
    # Example:
    #   network_mode: host
    #   # networks:
    #   #   - weather-sensors
    ###############################################################################
    # network_mode: host
    networks:
      - weather-sensors
    volumes:
      - sensor-data:/app/data
      - sensor-logs:/app/logs
      - sensor-config:/app/config
    ###############################################################################
    # ENVIRONMENT VARIABLES
    # Set broker_name and PUB_SOURCE as needed for your deployment
    ###############################################################################
    environment:
      - DEPLOYMENT_SCENARIO=home-lab
      - PUB_SOURCE=Mu
      - BROKER_NAME=n-vultr2
      - TZ=America/Los_Angeles
      - SERVICE=shelly
      - CONSOLE_LOG_LEVEL=INFO
      - FILE_LOG_LEVEL=DEBUG
      - CLEAR_LOG_FILE=true
      - MQTT_CONFIG_INFO={}
      - PUB_TOPIC_ROOT=KTBMES
      - SUB_TOPICS_SHELLY=Shelly/#
    labels:
      - "portainer.group=weather-sensors"
      - "portainer.service=shelly-processor"
      - "description=Shelly smart device processor service"
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/logs/shelly.log') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'
